### PR TITLE
GOOGLEDOCS-398: Build: Add Release Plugin

### PR DESCRIPTION
**Pull request by DenisGabriela**
- rename modules directories (no spaces)

The maven release plugin does not support paths with white spaces.

### CODE REVIEW

**Comment by montgolfiere** [comment]
Interesting limitation. Do you have a reference to a known issue in plugin docs ?

I must admit, I personally never use spaces in folders (or typically filenames) so doing this rename seems reasonable. Are we aware of any other impact, eg. broken links in documentation or otherwise ?

I assume we will also merge this rename commit back to at least master & develop. 

Do we also plan to merge back to SP/3.0.4.N as well (or will git track the rename in case we need to "cherry pick" a future hot fix to 3.0.4.x) ?

**Comment by CezarLeahu** [comment]
With our current naming of the module directories, the maven release plugin fails to execute the 'prepare' goal, with the error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project alfresco-GoogleDocs: An error is occurred in the checkin process: Exception while executing SCM command. Error while executing command. Error inside systemOut parser: Illegal character in path at index 0: "Google%20Docs%20Repository/pom.xml" -> [Help 1]
```

**Comment by CezarLeahu** [comment]
@montgolfiere Git does track renamed/moved files most of the time, but it's not very reliable.
To be on the safe side, we can either cherry-pick this commit on our other branches, or do the same directory renaming on those branches, also. I'm in favor of the latter option, as it would not depend on any other changes/commits.

**Comment by montgolfiere** [comment]
I think we agreed to merge back to at least: master, develop & SP/3.0.4.N.

Thanks

**Comment by DenisGabriela** [comment]
> I think we agreed to merge back to at least: master, develop & SP/3.0.4.N.

Done. All bamboo builds are green.

**Pull request merged**
